language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - '$HOME/.npm'
matrix:
  fast_finish: true
  include:
    - env: ECMAScript
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/backend-node-api
        - npm install
      script:
        - npm test
        - npm run build
    - env: TypeScript
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/frontend-react-app
        - npm install
      script:
        - npm test
        - npm run build
